Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Style/FormatString:
  EnforcedStyle: sprintf
AllCops:
  Exclude:
  - 'Rakefile'
  - 'bin/*'
  - 'dry-dock.gemspec'
  - 'examples/*'
  - 'spec/**/*'
  - 'vendor/**/*'
