sudo: required
services:
- docker
language: ruby
rvm:
- 2.1.5
before_install:
- docker version
- sudo service docker stop
- sudo dpkg -l | sort
- sudo apt-get purge lxc-docker-1.7.0
- curl -sSL https://get.docker.com/ | sudo sh
- docker version
- docker info
script: bundle exec rspec
addons:
  code_climate:
    repo_token: e1dfe86e3cc086b44532f7f1122f585fe828e141767ac41e833b365b21fd275a
