dist: trusty
sudo: required
language: ruby
rvm:
- 2.1.8
- 2.2.4
- 2.3.0
env:
  global:
  - DOCKER_HOME=/opt/docker
  matrix:
  - DOCKER_VERSION=1.7.1
  - DOCKER_VERSION=1.8.3
  - DOCKER_VERSION=1.9.1
before_install:
- gem install bundler
- scripts/install_docker
- scripts/start_docker
- scripts/gather_environment
after_failure:
- cat $DOCKER_HOME/logs/docker.log
script: bundle exec rspec
addons:
  code_climate:
    repo_token: e1dfe86e3cc086b44532f7f1122f585fe828e141767ac41e833b365b21fd275a
