sudo: required
services:
- docker
language: ruby
rvm:
- 2.1.5
before_install:
- apt-cache policy docker-engine
- apt-get install docker-engine=1.8.0
- docker version
- docker info
script: bundle exec rspec
