sudo: required
services:
- docker
language: ruby
rvm:
- 2.1.5
before_install:
- apt-cache search docker
- apt-cache policy docker-engine
- apt-get install docker-engine=1.8.0
- docker version
- docker info
script: bundle exec rspec
addons:
  code_climate:
    repo_token: e1dfe86e3cc086b44532f7f1122f585fe828e141767ac41e833b365b21fd275a
