#!/bin/bash
#
# Start an existing docker binary located under $DOCKER_HOME.
set -e
set -x

function version {
  echo "$@" | awk -F. '{ printf("%03d%03d%03d\n", $1, $2, $3); }'
}

sudo rm -f /var/run/docker.pid

if [ "$(version $DOCKER_VERSION)" -ge "$(version '1.9.0')" ]
then
  # Docker v1.9.0 and above changed the --daemon flag to a subcommand.
  sudo $DOCKER_HOME/docker-$DOCKER_VERSION daemon \
      --pidfile=/var/run/docker.pid \
      >$DOCKER_HOME/logs/docker.log 2>&1 &
else
  sudo $DOCKER_HOME/docker-$DOCKER_VERSION --daemon \
      --pidfile=/var/run/docker.pid \
      >$DOCKER_HOME/logs/docker.log 2>&1 &
fi
